name: build

on: [push, workflow_dispatch]

env:
  DOCKER_REGISTRY: ghcr.io
  DOCKER_REPO: ${{ github.repository_owner }}
  DOCKER_IMAGE: vscode-tunnel
  DOCKER_TAG: ${{ github.ref_name }}

jobs:
  build-docker:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Login to Docker registry
      uses: docker/login-action@v2
      with:
        registry: ${{ env.DOCKER_REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Build Docker image
      run: docker build -t "${DOCKER_REGISTRY}/${DOCKER_REPO,,}/${DOCKER_IMAGE}:${DOCKER_TAG}" .
    - name: Publish Docker image
      if: github.ref_name == 'master' || github.ref_type == 'tag'
      run: docker push "${DOCKER_REGISTRY}/${DOCKER_REPO,,}/${DOCKER_IMAGE}:${DOCKER_TAG}"
